lesson-2
yanisshkur/easy-learning pull request #4
Opened 2022-07-16 18:17 UTC by yanisshkur

2022-07-17 18:14 UTC, exoriri commented on lesson-2/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,700;1,400;1,500;1,700&family=Lato&family=Luxurious+Roman&family=Montserrat:ital,wght@1,200&family=Nunito:ital,wght@1,200&fami
Молодец, что добавил google fonts. Зайди туда еще раз и выбери только `Roboto`. Остальные нам не нужны.

2022-07-17 18:14 UTC, exoriri commented on lesson-2/css/style.css
> +    text-decoration: 3px underline #0187FC;
У нас в макете нигде нет text-decoration. Нужно **убрать**.

2022-07-17 18:14 UTC, exoriri commented on lesson-2/css/style.css
> +    left: 220px;
Янис, убери `left: 220px`. top у нас в макете `20px`, а не `289px`. Задай классу `content__form` `position: relative`

Сделай это в первую очередь. Тогда страница не будет ползти.

2022-07-17 18:14 UTC, exoriri commented on lesson-2/css/style.css
>  }
Убери это, пожалуйста. У нас нигде этого нет.

2022-07-17 18:14 UTC, exoriri commented on lesson-2/css/style.css
>  }
Что это?:))) Убери, пожалуйста.

2022-07-17 18:14 UTC, exoriri commented on lesson-2/css/style.css
> +
Убери это, пожалуйста

2022-07-17 18:14 UTC, exoriri commented on lesson-2/css/style.css
> +.images__section {
У тебя два раза в css объявлен класс `images__section`

2022-07-17 18:14 UTC, exoriri commented on lesson-2/css/style.css
> +    text-decoration: 3px underline #fff;
Убери этот `text-decoration`

2022-07-17 18:14 UTC, exoriri commented on lesson-2/css/style.css
> +}
Убери это, пожалуйста

2022-07-17 18:14 UTC, exoriri commented on lesson-2/css/style.css
> +}
Убери это, пожалуйста

2022-07-17 18:14 UTC, exoriri commented on lesson-2/css/style.css
> +    left: 260px;
убери этот absolute он тут не нужен

2022-07-17 18:14 UTC, exoriri commented on lesson-2/css/style.css
> +}
Убери это, пожалуйста

2022-07-17 18:14 UTC, exoriri commented on lesson-2/css/style.css
>  }
Убери это, пожалуйста

2022-07-17 18:14 UTC, exoriri commented on lesson-2/index.html
> +            <div class="footer__box">
footer__box, а родительского класса footer нет.

2022-07-17 18:14 UTC, exoriri commented on lesson-2/index.html
> +                <p class="footer__wrapper__p">Не могу найти нужные анализы</p>
Вижу прочитал БЭМ молодец. Когда ты хочешь называть элемент в элементе. Нужно только один раз делать **двойную черточку**
То есть `footer-wrapper__p`.

Вообще переименуй все стили по тому, что они делают. Я бы назвал это `footer__additional-text`

2022-07-17 18:25 UTC, exoriri requested changes
Переименуй все иконки нормальными названиями. `Не vector(1).svg`

Перемести svg файл из images в icon

2022-07-20 04:16 UTC, yanisshkur commented on lesson-2/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,700;1,400;1,500;1,700&family=Lato&family=Luxurious+Roman&family=Montserrat:ital,wght@1,200&family=Nunito:ital,wght@1,200&fami
Готово done

2022-07-20 04:17 UTC, yanisshkur commented on lesson-2/css/style.css
> +    text-decoration: 3px underline #0187FC;
Готово done

2022-07-20 04:42 UTC, yanisshkur commented on lesson-2/css/style.css
> +    left: 220px;
Готово done

2022-07-20 04:42 UTC, yanisshkur commented on lesson-2/css/style.css
>  }
Готово done

2022-07-20 04:44 UTC, yanisshkur commented on lesson-2/css/style.css
>  }
Готово done

2022-07-20 04:51 UTC, yanisshkur commented on lesson-2/css/style.css
> +    left: 260px;
Готово done

2022-07-20 05:07 UTC, yanisshkur commented on lesson-2/index.html
> +                <p class="footer__wrapper__p">Не могу найти нужные анализы</p>
Готово done

2022-07-20 05:08 UTC, yanisshkur commented on lesson-2/index.html
> +            <div class="footer__box">
Готово done

2022-07-20 05:08 UTC, yanisshkur commented on lesson-2/css/style.css
>  }
готово done

2022-07-20 05:08 UTC, yanisshkur commented on lesson-2/css/style.css
> +}
готово done

2022-07-20 05:09 UTC, yanisshkur commented on lesson-2/css/style.css
> +    left: 260px;
Готово done

2022-07-23 11:33 UTC, merged